version: '3.7'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
  postgres:
    container_name: postgres
    image: postgres:11
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: pledges
      POSTGRES_PASSWORD: $LOCAL_PG_PASS
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
    external: true