version: '2'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:11
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: pledges
      POSTGRES_PASSWORD: $LOCAL_PG_PASS
    ports:
      - "5432:5432"